version: "2.3"

services:
  # Build base image
  build-notebook:
    image: jupyter/notebook:builder
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: builder
    command: echo "built" # This prevents the default command from running (i.e. jupyter notebook)

  # Run jupyter notebook (for editing)
  run-notebook:
    image: jupyter/notebook:run
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: run
      cache_from:
        - jupyter/notebook:builder
    volumes:
      - ../:/home/jovyan/work
    ports:
      - "8888:8888"

  # Run voila server
  voila:
    image: jupyter/voila
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: deploy
      cache_from:
        - jupyter/notebook:builder
    volumes:
      - ../:/home/jovyan/work
    expose:
      - 8866
    command: ./run_voila

  # Run nginx and connect to voila container
  nginx:
    image: nginx-voila
    build:
      context: ../nginx
      dockerfile: ../docker/Dockerfile.nginx
    restart: unless-stopped
    container_name: nginx
    links:
      - voila # required for the nginx configuration
    ports:
      - 80:80
    volumes:
      - ../nginx/conf.d/:/etc/nginx/conf.d/
