#!/usr/bin/env bash

cd ../docker
# Remove containers if already running
docker-compose \
	--file docker-compose.nginx.yml --file docker-compose.build.yml --file docker-compose.voila.yml \
	rm -fsv
docker-compose \
	--file docker-compose.nginx.yml --file docker-compose.build.yml --file docker-compose.voila.yml \
	down
# Build and spin
docker-compose \
	--file docker-compose.nginx.yml --file docker-compose.build.yml --file docker-compose.voila.yml \
	up --build --remove-orphans
