#!/usr/bin/env bash

cd ../docker
# Remove containers if already running
docker-compose rm -fsv build-notebook run-notebook
# Build and spin
docker-compose up --build --remove-orphans build-notebook run-notebook
